config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

#Omniauth
get '/auth/:provider/callback', to: 'sessions#omniauth'

#root page
get '/', to: 'sessions#welcome'

#login and logout
get '/login', to: 'sessions#new'
post '/login', to: 'sessions#create'
delete '/logout', to: 'sessions#destroy'

#signup
get 'signup', to: 'users#new'
post 'signup', to: 'users#create'

#nested routes
resources :categories, only: [:index, :new, :create, :show] do
  resources :photos
end

resources :users, only: [:new, :create, :show] do
  resources :photos, only:[:index, :new, :create, :edit, :destroy]
end

resources :photos

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :photos
    has_many :users, through: :photos
    
    validates :name, uniqueness: true
    
    scope :alpha, -> {order(:name)}

    
end

app/models/catergory.rb
class Catergory < ApplicationRecord
    has_many :photos
    has_many :users, through: :photos
end

app/models/photo.rb
class Photo < ApplicationRecord
    belongs_to :user
    belongs_to :category

    has_one_attached :image
    
    validates :title, presence: true
    validates :caption, presence: true
    validates :caption, length: { maximum: 250 }
end

app/models/user.rb
class User < ApplicationRecord
    has_many :photos
    has_many :categories, through: :photos
    
    has_secure_password
    
    validates :username, presence: true
    validates :username, uniqueness: true
    

    def self.from_omniauth(response)
        User.find_or_create_by(uid: response[:uid], provider: response[:provider]) do |u|
            u.username = response[:info][:name]
            u.password = SecureRandom.hex(16)
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?, :redirect_if_not_logged_in

    private

        def current_user
            @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
        end

        def logged_in?
            !!session[:user_id]
        end

        def redirect_if_not_logged_in
            redirect_to login_path if !logged_in?
        end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :redirect_if_not_logged_in

    def index
        @categories = Category.all.alpha
    end 

    def new
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)
        if @category.save
            redirect_to categories_path(@category)
        else
            render :new
        end
    end

    private

    def category_params
        params.require(:category).permit(:name)
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
    before_action :set_photo, only:[:show, :edit, :update]
    before_action :redirect_if_not_logged_in

    def index
        if params[:category_id] && @category = Category.find_by_id(params[:category_id])
            @photos = @category.photos
        else
            @photos = Photo.all
        end
    end

    def new
        @photo = Photo.new
        @photo.build_category
    end

    def create
        @photo = current_user.photos.build(photo_params)
        if @photo.save
            redirect_to photo_path(@photo)
        else
            @category = Category.find_by_id(params[:category_id]) if params[:category_id]
            render :new, alert: "Invalid information."
        end
    end

    def show
        
    end

    def edit
       
    end

    def update
        if @photo.valid?
            @photo.update(photo_params)
            redirect_to photo_path(@photo)
        else
            render :edit, alert: "Invalid information."
        end
    end

    def destroy
        photo = Photo.find(params[:id])
        photo.destroy
        redirect_to photos_path
    end

    private

        def photo_params
            params.require(:photo).permit(:title, :caption, :image, :category_id)
        end

        def set_photo
            @photo = Photo.find_by_id(params[:id])
            redirect_to photos_path if !@photo
        end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
#login user, logout user, omniauth
    def welcome
    end
    
    def new
        @user = User.new
    end

    def create
        @user = User.find_by(username: params[:username])
        if @user && @user.authenticate(params[:password])
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            flash[:message] = "Invalid username or password. Please try again" 
            redirect_to '/login'
        end
    end

    def destroy 
        session.delete(:user_id)
        redirect_to '/'
    end
    
    def omniauth
        #log users in from omniauth
        #binding.pry
        user = User.from_omniauth(request.env['omniauth.auth'])
        if user.valid?
            session[:user_id] = user.id 
            redirect_to user_path(user)
        else 
            flash[:message] = user.errors.full_message.join(". ")
            redirect_to '/login'
        end
    end

    private
        def auth 
            request.env['omniauth.auth']
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new 
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else 
            render :new
        end 
    end

    def show 
        @user = User.find(params[:id])
        @photos = @user.photos
    end
    
    private 

        def user_params 
            params.require(:user).permit(:username, :password)
        end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catergories_helper.rb
module CatergoriesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<h1>All Categories</h1>
<div>
<% @categories.each do |c| %>
    <h3><li><%= link_to c.name, category_photos_path(c) %></li></h3>
    <%= link_to "Add New Photo", new_category_photo_path(c) %>
    <hr>
<% end %>
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render partial: 'layouts/errors', locals: {object: @category}  %> 

<%= form_for @category do |f| %>
    <%= f.label :name %>:
    <%= f.text_field :name %>
    <br>
    <%= f.submit %>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.name%></h1>
<div>
<% @category.photos.each do |cp|%>
<% if cp.image.attached? %>
   <%= image_tag url_for cp.image.variant(resize_to_fill: [640, 480]) %>
<% end %>
<h2><%= link_to cp.title, photo_path(cp)%></h2>
<% end %>
</div>

 <%= link_to "Upload A Photo", new_photo_path%>

app/views/layouts/_errors.html.erb
  <% if object.errors.any? %>
    <div id="error_explanation">
       <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>
        <ul>
            <% object.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photography</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
  <div class="wrapper">
   <style> h1 {text-align: center;}
          p {text-align: center;}
          div {text-align: center;}
    </style>
  <% if logged_in? %>
    <nav class='navbar'>
  <%= link_to 'Categories', categories_path, class:'button'%> |
  <%= link_to 'View My Photos', photos_path, class:'button'%> |
  <%= link_to "Upload Photo", new_photo_path, class:'button'%> |
  <%= link_to "Logout", logout_path, method: :delete, class:'button' %>
  </nav>
     <% else %>
      <%= link_to 'Login', login_path %> or <%= link_to "Signup", signup_path%>
    <% end %>
    <br>
    <%= yield %>
    <br><br>
      <footer class="branding">
        <small>&copy; 2020 <strong>MDPHOTOGRAPHY</strong></small>
      </footer>
    </div>
  </body>
</html>

app/views/photos/_form.html.erb
<%= link_to "Add new Category", new_category_path %>

<%= form_for([@category, @photo]) do |f| %>
    <%= f.label :image %>
    <%= f.file_field :image %>
    <br>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <br>
    <%= f.label :caption%>
    <%= f.text_field :caption%>
    <br>
    <%= f.label :category, "Select a Category:" %>
    <%= f.collection_select :category_id, Category.all, :id, :name, include_blank: 'Select One' %>
    <br>
    
    <%= f.submit %>
<% end %> 

app/views/photos/edit.html.erb
<h1>Edit Photo</h1>
<%= render partial: 'layouts/errors', locals: {object: @photo}  %>
<br>
<%= render 'form' %>

app/views/photos/index.html.erb
<h1>Photos</h1>
<%= link_to "Upload A Photo", new_photo_path%>
<div>
<% @photos.each do |photo|%>
<% if photo.image.attached? %>
   <%= image_tag url_for photo.image.variant(resize_to_fill: [640, 480]) %>
<% end %>
<h2><%= link_to photo.title, photo_path(photo)%></h2>
<h3>Category: <%= photo.category.name%></h3>
<p>Caption: <%= photo.caption %></p>
<hr>
<% end %>
</div>

app/views/photos/new.html.erb
<h1>New Photos</h1>
<%= render partial: 'layouts/errors', locals: {object: @photo}  %>
<%= render 'form' %>

app/views/photos/show.html.erb
<h1><%=@photo.title%></h1>

<% if @photo.image.attached? %>
   <%= image_tag url_for @photo.image.variant(resize_to_fill: [640, 480])   %>
<% end %>

<h3>Category: <%= link_to @photo.category.name, category_photos_path(@photo.category) %></h3>
<h3>Caption: <%=@photo.caption%></h3>

<%= link_to "Edit Photo", edit_photo_path(@photo)%> | 
<%= link_to "Delete Photo", photo_path(@photo), method: 'delete'%>

app/views/users/new.html.erb
<h2>Sign Up</h2>

<%= render partial: 'layouts/errors', locals: {object: @user}  %> 

<%=form_for (@user) do |f|%>
   <%=f.label :username%><br>
   <%=f.text_field :username%><br><br>
   
   <%=f.label :password%><br>
   <%=f.password_field :password%><br><br>

   <%=f.submit "Sign Up"%>
<%end%>

app/views/users/show.html.erb
<h1>Welcome, <%= @user.username %></h1>


<h2>Photos:</h2>
<% @user.photos.each do |photo| %>
<% if photo.image.attached? %>
   <%= image_tag url_for photo.image.variant(resize_to_fill: [640, 480])   %>
<% end %>
  <li><%= link_to photo.title, photo_path(photo)%></li>
 <% end %> 